# Reference for influxdb2: https://docs.influxdata.com/influxdb/v2/install/use-docker-compose/
# Reference for Grafana: https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
# Reference for Nginx: https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

services:
  grafana:
    image: grafana/grafana:12.0.1-ubuntu
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      monitoring:
        ipv4_address: 172.28.0.2

  influxdb2:
    image: influxdb:2.7.12
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    networks:
      monitoring:
        ipv4_address: 172.28.0.3
  # Uncomment the following lines to enable Nginx as a reverse proxy
  # nginx:
  #     image: nginx:1.27.5-bookworm
  #     depends_on:
  #       - grafana
  #       - influxdb2
  #     ports:
  #       - "80:80"
  #       - "443:443"
  #     volumes:
  #       - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #       - ./certs:/etc/nginx/certs:ro
  #     healthcheck:
  #       test: ["CMD", "curl", "-f", "http://localhost"]
  #       interval: 30s
  #       timeout: 10s
  #       retries: 3
  #     networks:
  #       monitoring:
  #         ipv4_address: 172.20.0.4

secrets:
  influxdb2-admin-username:
    file: ./secrets/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ./secrets/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ./secrets/.env.influxdb2-admin-token

volumes:
  grafana-storage: {}

  influxdb2-data:
  influxdb2-config:

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.18.0.1