apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb2:8086
    basicAuth: false
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: testbucket
      tlsSkipVerify: true
    secureJsonData:
      token: ADD_YOUR_INFLUXDB2_ADMIN_TOKEN_HERE
    isDefault: true
    editable: true
    readOnly: false